export enum ErrorCode {
  TRANSACTION_NOT_FOUND = "TRANSACTION_NOT_FOUND",
  TRANSACTION_FAILED = "TRANSACTION_FAILED",
  WRONG_CONTRACT = "WRONG_CONTRACT",
  ORDER_MISMATCH = "ORDER_MISMATCH",
  INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS",
  RECEIPT_ALREADY_USED = "RECEIPT_ALREADY_USED",
  INVALID_RECEIPT = "INVALID_RECEIPT",
  MISSING_RECEIPT = "MISSING_RECEIPT",
  TOKEN_NOT_ACCEPTED = "TOKEN_NOT_ACCEPTED",
  INTERNAL_ERROR = "INTERNAL_ERROR"
}
