export enum ErrorCode {
  RPC_ERROR = "RPC_ERROR",
  INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS",
  AMOUNT_TOO_LOW = "AMOUNT_TOO_LOW",
  TOKEN_NOT_ACCEPTED = "TOKEN_NOT_ACCEPTED",
  TRANSACTION_FAILED = "TRANSACTION_FAILED",
  DUPLICATE_TRANSACTION = "DUPLICATE_TRANSACTION",
  INVALID_RECEIPT = "INVALID_RECEIPT",
  INTERNAL_ERROR = "INTERNAL_ERROR",
  // Verification specific
  TRANSACTION_NOT_FOUND = "TRANSACTION_NOT_FOUND",
  WRONG_CONTRACT = "WRONG_CONTRACT",
  ORDER_MISMATCH = "ORDER_MISMATCH",
  RECEIPT_ALREADY_USED = "RECEIPT_ALREADY_USED",
  MISSING_RECEIPT = "MISSING_RECEIPT"
}

export class PayNodeException extends Error {
  constructor(public message: string, public code: ErrorCode, public details?: any) {
    super(message);
    this.name = "PayNodeException";
  }
}
