/** Generated by scripts/sync-config.py */
export enum ErrorCode {
  RpcError = "rpc_error",
  InsufficientFunds = "insufficient_funds",
  AmountTooLow = "amount_too_low",
  TokenNotAccepted = "token_not_accepted",
  TransactionFailed = "transaction_failed",
  DuplicateTransaction = "duplicate_transaction",
  InvalidReceipt = "invalid_receipt",
  InternalError = "internal_error",
  TransactionNotFound = "transaction_not_found",
  WrongContract = "wrong_contract",
  OrderMismatch = "order_mismatch",
  MissingReceipt = "missing_receipt",
}

export const ERROR_MESSAGES: Record<string, string> = {
  "rpc_error": "Failed to connect to any provided RPC nodes.",
  "insufficient_funds": "Wallet lacks USDC or ETH for gas.",
  "amount_too_low": "Payment amount is below the protocol minimum (1000).",
  "token_not_accepted": "The provided token address is not in the whitelist.",
  "transaction_failed": "On-chain transaction reverted or failed.",
  "duplicate_transaction": "This transaction hash has already been consumed.",
  "invalid_receipt": "The provided receipt (TxHash) is malformed or invalid.",
  "internal_error": "An unexpected error occurred.",
  "transaction_not_found": "Transaction not found on-chain.",
  "wrong_contract": "Payment event was not emitted by the official PayNode contract.",
  "order_mismatch": "OrderId in receipt does not match requested ID.",
  "missing_receipt": "Please pay to PayNode contract and provide 'X-402-Payload' header.",
};

export class PayNodeException extends Error {
  constructor(public code: ErrorCode, message?: string, public details?: any) {
    const finalMessage = message || ERROR_MESSAGES[code] || "An unexpected error occurred.";
    super(finalMessage);
    this.name = "PayNodeException";
    this.message = finalMessage;
  }
}
