/** Generated by scripts/sync-config.py */
export const PAYNODE_ROUTER_ADDRESS = "0x4A73696ccF76E7381b044cB95127B3784369Ed63";
export const PAYNODE_ROUTER_ADDRESS_SANDBOX = "0x24cD8b68aaC209217ff5a6ef1Bf55a59f2c8Ca6F";
export const BASE_USDC_ADDRESS = "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913";
export const BASE_USDC_ADDRESS_SANDBOX = "0x109AEddD656Ed2761d1e210E179329105039c784";
export const PROTOCOL_TREASURY = "0x598bF63F5449876efafa7b36b77Deb2070621C0E";
export const PROTOCOL_FEE_BPS = 100;
export const MIN_PAYMENT_AMOUNT = BigInt(1000);

export const BASE_RPC_URLS = ["https://mainnet.base.org", "https://base.meowrpc.com", "https://1rpc.io/base"];
export const BASE_RPC_URLS_SANDBOX = ["https://sepolia.base.org", "https://base-sepolia-rpc.publicnode.com"];

export const ACCEPTED_TOKENS: Record<number, string[]> = {
    8453: ["0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"],
    84532: ["0x109AEddD656Ed2761d1e210E179329105039c784"]
};
